"""Minimal stub for the Windows-only MetaTrader5 package used inside the Wine container.

The host Linux environment does not install this package; the stub prevents
host-side type checkers from treating the import as Unknown.
"""

from __future__ import annotations

from typing import Any

__version__: str

def initialize(*args: Any, **kwargs: Any) -> Any: ...
def shutdown(*args: Any, **kwargs: Any) -> Any: ...
def terminal_info(*args: Any, **kwargs: Any) -> Any: ...
def version(*args: Any, **kwargs: Any) -> Any: ...
def login(*args: Any, **kwargs: Any) -> Any: ...
def copy_rates_from_pos(*args: Any, **kwargs: Any) -> Any: ...
def copy_rates_from(*args: Any, **kwargs: Any) -> Any: ...
def copy_rates_range(*args: Any, **kwargs: Any) -> Any: ...
def copy_ticks_from(*args: Any, **kwargs: Any) -> Any: ...
def copy_ticks_range(*args: Any, **kwargs: Any) -> Any: ...
def orders_total(*args: Any, **kwargs: Any) -> Any: ...
def orders_get(*args: Any, **kwargs: Any) -> Any: ...
def positions_total(*args: Any, **kwargs: Any) -> Any: ...
def positions_get(*args: Any, **kwargs: Any) -> Any: ...
def history_orders_total(*args: Any, **kwargs: Any) -> Any: ...
def history_orders_get(*args: Any, **kwargs: Any) -> Any: ...
def history_deals_total(*args: Any, **kwargs: Any) -> Any: ...
def history_deals_get(*args: Any, **kwargs: Any) -> Any: ...
def order_send(*args: Any, **kwargs: Any) -> Any: ...
def order_check(*args: Any, **kwargs: Any) -> Any: ...
def symbol_info(*args: Any, **kwargs: Any) -> Any: ...
def symbol_info_tick(*args: Any, **kwargs: Any) -> Any: ...
def symbol_select(*args: Any, **kwargs: Any) -> Any: ...
def market_book_add(*args: Any, **kwargs: Any) -> Any: ...
def market_book_get(*args: Any, **kwargs: Any) -> Any: ...
def market_book_release(*args: Any, **kwargs: Any) -> Any: ...
def symbols_get(*args: Any, **kwargs: Any) -> Any: ...
def symbol_total(*args: Any, **kwargs: Any) -> Any: ...
