"""
This type stub file was generated by pyright.
"""

import grpc
import pytest
from dataclasses import dataclass
from typing import TYPE_CHECKING
from mt5linux import mt5_pb2_grpc
from collections.abc import Generator

"""Pytest fixtures for mt5docker container tests.

This module provides fixtures that automatically start and validate
the ISOLATED test container (mt5docker-test on port 48812).

The container is completely isolated from:
- Production (mt5, port 8001)
- tests.(neptor-mt5-test, port 18812)
- mt5linux tests (mt5linux-test, port 28812)

Test container configuration uses MT5DOCKER_TEST_* variables so root workspace
MT5_* runtime settings cannot leak into this isolated container. See
.env.example for setup instructions.

Test Categories:
- Config tests: Run without container (just verify configuration values)
- Container tests: Require running container (skip if no credentials)
"""
__all__: list[str] = ...
if TYPE_CHECKING:
    ...
_timing_start: float = ...
_current_phase: str = ...
_project_root = ...
@dataclass
class DockerContainerConfig:
    """Configuration for the test container."""
    container_name: str
    grpc_port: int
    vnc_port: int
    health_port: int
    startup_timeout: int
    grpc_timeout: int
    login: str | None
    password: str | None
    server: str
    auto_create_demo: bool
    ...


def get_test_container_config() -> DockerContainerConfig:
    """Get test container configuration from environment."""
    ...

_config = ...
_logger = ...
def has_mt5_credentials() -> bool:
    """Check if MT5 credentials are configured."""
    ...

def can_start_mt5_container() -> bool:
    """Check if tests have a supported MT5 startup path."""
    ...

def is_container_running(name: str | None = ...) -> bool:
    """Check if container is running."""
    ...

def is_grpc_service_ready(host: str = ..., port: int | None = ..., timeout: float = ...) -> bool:
    """Check if gRPC service is ready (actual handshake, not just port)."""
    ...

def wait_for_grpc_service(host: str = ..., port: int | None = ..., timeout: int | None = ...) -> bool:
    """Wait for gRPC service to become ready using progressive backoff."""
    ...

def start_test_container() -> None:
    """Start test container if not already running."""
    ...

@pytest.fixture(scope="session")
def docker_container() -> None:
    """Ensure test container is running (session-scoped).

    This fixture is NOT autouse - only tests that need the container
    will trigger container startup via dependent fixtures.

    Starts container if not already running.
    Reuses existing container if healthy.
    Does NOT clean up after tests - container stays running for reuse.

    Skips if:
    - SKIP_DOCKER=1 environment variable is set
    - MT5 credentials are not configured in .env file
    """
    ...

@pytest.fixture(scope="session")
def container_name(docker_container: None) -> str:
    """Provide test container name (requires container)."""
    ...

@pytest.fixture(scope="session")
def grpc_port(docker_container: None) -> int:
    """Provide test gRPC port (requires container)."""
    ...

@pytest.fixture(scope="session")
def health_port(docker_container: None) -> int:
    """Provide test health port (requires container)."""
    ...

@pytest.fixture(scope="session")
def vnc_port(docker_container: None) -> int:
    """Provide test VNC port (requires container)."""
    ...

@pytest.fixture
def grpc_channel(docker_container: None) -> Generator[grpc.Channel]:
    """Provide gRPC channel to test container."""
    ...

@pytest.fixture
def mt5_stub(grpc_channel: grpc.Channel) -> mt5_pb2_grpc.MT5ServiceStub:
    """Provide MT5Service stub via gRPC."""
    ...

@pytest.fixture
def mt5_service(grpc_channel: grpc.Channel) -> mt5_pb2_grpc.MT5ServiceStub:
    """Provide MT5Service stub via gRPC (alias for mt5_stub)."""
    ...

